### ISSUE TITLE
out of sync docker hub - openshift/jenkins-2-centos7:latest

### ISSUE THREAD

**Issue by tbugfinder** [openshift/jenkins#993]
Hi,

`docker pull openshift/jenkins-2-centos7`doesn't  load the `latest` which seems to be v3.11. Instead the Jenkins inside is 2.150.2.

**Comment by akram** [comment]
Hi @tbugfinder 
thank you for reporting this.
It is now fixed see https://hub.docker.com/r/openshift/jenkins-2-centos7

Also, our publishing in docker hub is deprecated and I suggest you to move to :
quay.io/openshift/origin-jenkins

**Comment by tbugfinder** [comment]
HI @akram 
it looks like tag `latest` is still not pointing to latest on hub.docker.com.

quay.io doesn't list jenkins-2-centos7 for OCP3.x or I didn't find it.

Thanks.

**Comment by akram** [comment]
@tbugfinder you must target the tag version that you need, so v3.11 probably in your case.

**Comment by tbugfinder** [comment]
Hey @akram !
I understand that the given tag releases the expected version.
However what's the reasonable of not mapping latest to v3.11 ?


Thanks.

**Comment by akram** [comment]
@tbugfinder : latest cannot point to v3.11 in our case, because we release also images for 4.x branch of OpenShift which are the latests.
3.11 tag is for maintenance only now. We are updating this tag to publish CVEs and major fixes....and sometimes some minor improvements that we can backport easily.
